using System.Collections.Generic;
using Raspicam.Net.Native.Parameters;

namespace Raspicam.Net.Mmal
{
    internal static class MmalParameterHelpers
    {
        public static IReadOnlyCollection<Parameter> ParameterHelper = new List<Parameter>
        {
            new Parameter(MmalParametersCamera.MmalParameterAntishake, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_ANTISHAKE"),
            new Parameter(MmalParametersCamera.MmalParameterBrightness, typeof(MmalParameterRationalType), "MMAL_PARAMETER_BRIGHTNESS"),
            new Parameter(MmalParametersCommon.MmalParameterBufferFlagFilter, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_BUFFER_FLAG_FILTER"),
            new Parameter(MmalParametersCamera.MmalParameterCameraBurstCapture, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_CAMERA_BURST_CAPTURE"),
            new Parameter(MmalParametersCamera.MmalParameterCameraCustomSensorConfig, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_CAMERA_CUSTOM_SENSOR_CONFIG"),
            new Parameter(MmalParametersCamera.MmalParameterCameraMinIso, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_CAMERA_MIN_ISO"),
            new Parameter(MmalParametersCamera.MmalParameterCameraNum, typeof(MmalParameterInt32Type), "MMAL_PARAMETER_CAMERA_NUM"),
            new Parameter(MmalParametersCamera.MmalParameterCaptureExposureComp, typeof(MmalParameterInt32Type), "MMAL_PARAMETER_CAPTURE_EXPOSURE_COMP"),
            new Parameter(MmalParametersCamera.MmalParameterCapture, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_CAPTURE"),
            new Parameter(MmalParametersCamera.MmalParameterCaptureStatsPass, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_CAPTURE_STATS_PASS"),
            new Parameter(MmalParametersClock.MmalParameterClockActive, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_CLOCK_ACTIVE"),
            new Parameter(MmalParametersClock.MmalParameterClockEnableBufferInfo, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_CLOCK_ENABLE_BUFFER_INFO"),
            new Parameter(MmalParametersClock.MmalParameterClockFrameRate, typeof(MmalParameterRationalType), "MMAL_PARAMETER_CLOCK_FRAME_RATE"),
            new Parameter(MmalParametersClock.MmalParameterClockScale, typeof(MmalParameterRationalType), "MMAL_PARAMETER_CLOCK_SCALE"),
            new Parameter(MmalParametersClock.MmalParameterClockTime, typeof(MmalParameterInt64Type), "MMAL_PARAMETER_CLOCK_TIME"),
            new Parameter(MmalParametersCamera.MmalParameterContrast, typeof(MmalParameterRationalType), "MMAL_PARAMETER_CONTRAST"),
            new Parameter(MmalParametersCamera.MmalParameterDpfConfig, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_DPF_CONFIG"),
            new Parameter(MmalParametersCamera.MmalParameterEnableRawCapture, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_ENABLE_RAW_CAPTURE"),
            new Parameter(MmalParametersCamera.MmalParameterExifDisable, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_EXIF_DISABLE"),
            new Parameter(MmalParametersCamera.MmalParameterExposureComp, typeof(MmalParameterInt32Type), "MMAL_PARAMETER_EXPOSURE_COMP"),
            new Parameter(MmalParametersVideo.MmalParameterExtraBuffers, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_EXTRA_BUFFERS"),
            new Parameter(MmalParametersCamera.MmalParameterFlashRequired, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_FLASH_REQUIRED"),
            new Parameter(MmalParametersCamera.MmalParameterFrameRate, typeof(MmalParameterRationalType), "MMAL_PARAMETER_FRAME_RATE"),
            new Parameter(MmalParametersVideo.MmalParameterIntraperiod, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_INTRAPERIOD"),
            new Parameter(MmalParametersCamera.MmalParameterIso, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_ISO"),
            new Parameter(MmalParametersCamera.MmalParameterJpegAttachLog, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_JPEG_ATTACH_LOG"),
            new Parameter(MmalParametersCamera.MmalParameterJpegQFactor, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_JPEG_Q_FACTOR"),
            new Parameter(MmalParametersCommon.MmalParameterLockstepEnable, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_LOCKSTEP_ENABLE"),
            new Parameter(MmalParametersVideo.MmalParameterMbRowsPerSlice, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_MB_ROWS_PER_SLICE"),
            new Parameter(MmalParametersVideo.MmalParameterMinimiseFragmentation, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_MINIMISE_FRAGMENTATION"),
            new Parameter(MmalParametersCommon.MmalParameterNoImagePadding, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_NO_IMAGE_PADDING"),
            new Parameter(MmalParametersCommon.MmalParameterPowermonEnable, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_POWERMON_ENABLE"),
            new Parameter(MmalParametersCamera.MmalParameterRotation, typeof(MmalParameterInt32Type), "MMAL_PARAMETER_ROTATION"),
            new Parameter(MmalParametersCamera.MmalParameterSaturation, typeof(MmalParameterRationalType), "MMAL_PARAMETER_SATURATION"),
            new Parameter(MmalParametersCamera.MmalParameterSharpness, typeof(MmalParameterRationalType), "MMAL_PARAMETER_SHARPNESS"),
            new Parameter(MmalParametersCamera.MmalParameterShutterSpeed, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_SHUTTER_SPEED"),
            new Parameter(MmalParametersCamera.MmalParameterStillsDenoise, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_STILLS_DENOISE"),
            new Parameter(MmalParametersCamera.MmalParameterSwSaturationDisable, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_SW_SATURATION_DISABLE"),
            new Parameter(MmalParametersCamera.MmalParameterSwSharpenDisable, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_SW_SHARPEN_DISABLE"),
            new Parameter(MmalParametersCommon.MmalParameterSystemTime, typeof(MmalParameterUint64Type), "MMAL_PARAMETER_SYSTEM_TIME"),
            new Parameter(MmalParametersVideo.MmalParameterVideoAlignHoriz, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ALIGN_HORIZ"),
            new Parameter(MmalParametersVideo.MmalParameterVideoAlignVert, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ALIGN_VERT"),
            new Parameter(MmalParametersVideo.MmalParameterVideoBitRate, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_BIT_RATE"),
            new Parameter(MmalParametersCamera.MmalParameterVideoDenoise, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_DENOISE"),
            new Parameter(MmalParametersVideo.MmalParameterVideoDroppablePframes, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_DROPPABLE_PFRAMES"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeFrameLimitBits, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_FRAME_LIMIT_BITS"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeInitialQuant, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_INITIAL_QUANT"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeInlineHeader, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_ENCODE_INLINE_HEADER"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeInlineVectors, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_ENCODE_INLINE_VECTORS"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeMaxQuant, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_MAX_QUANT"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeMinQuant, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_MIN_QUANT"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodePeakRate, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_PEAK_RATE"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeQpP, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_QP_P"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeRcSliceDquant, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_ENCODE_RC_SLICE_DQUANT"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeSeiEnable, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_ENCODE_SEI_ENABLE"),
            new Parameter(MmalParametersVideo.MmalParameterVideoEncodeSpsTimings, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_ENCODE_SPS_TIMINGS"),
            new Parameter(MmalParametersVideo.MmalParameterVideoFrameRate, typeof(MmalParameterRationalType), "MMAL_PARAMETER_VIDEO_FRAME_RATE"),
            new Parameter(MmalParametersVideo.MmalParameterVideoImmutableInput, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_IMMUTABLE_INPUT"),
            new Parameter(MmalParametersVideo.MmalParameterVideoInterpolateTimestamps, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_INTERPOLATE_TIMESTAMPS"),
            new Parameter(MmalParametersVideo.MmalParameterVideoMaxNumCallbacks, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_VIDEO_MAX_NUM_CALLBACKS"),
            new Parameter(MmalParametersVideo.MmalParameterVideoRequestIFrame, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_REQUEST_I_FRAME"),
            new Parameter(MmalParametersCamera.MmalParameterVideoStabilisation, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_VIDEO_STABILISATION"),
            new Parameter(MmalParametersCommon.MmalParameterZeroCopy, typeof(MmalParameterBooleanType), "MMAL_PARAMETER_ZERO_COPY"),
            new Parameter(MmalParametersCamera.MmalParameterJpegRestartInterval, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_JPEG_RESTART_INTERVAL"),
            new Parameter(MmalParametersCamera.MmalParameterCameraIspBlockOverride, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_CAMERA_ISP_BLOCK_OVERRIDE"),
            new Parameter(MmalParametersCamera.MmalParameterBlackLevel, typeof(MmalParameterUint32Type), "MMAL_PARAMETER_BLACK_LEVEL"),
            new Parameter(MmalParametersCamera.MmalParameterOutputShift, typeof(MmalParameterInt32Type), "MMAL_PARAMETER_OUTPUT_SHIFT"),
            new Parameter(MmalParametersCamera.MmalParameterCcmShift, typeof(MmalParameterInt32Type), "MMAL_PARAMETER_CCM_SHIFT"),
            new Parameter(MmalParametersCamera.MmalParameterAnalogGain, typeof(MmalParameterRationalType), "MMAL_PARAMETER_ANALOG_GAIN"),
            new Parameter(MmalParametersCamera.MmalParameterDigitalGain, typeof(MmalParameterRationalType), "MMAL_PARAMETER_DIGITAL_GAIN")
        };
    }
}
